### ISSUE TITLE
似乎无法认证有线网

### ISSUE THREAD

**Issue by Amaterasu33** [robertying/dotNetCampus#1]
学校这个有线网认证改的很迷啊...目前还没发现能用的客户端

**Comment by robertying** [comment]
学校用的私有协议，不过现在已经有了python实现，详见 [tunet-python](https://github.com/yuantailing/tunet-python)。
过段时间可能就根据这个写进app了。

**Comment by Amaterasu33** [comment]
了解，感谢

**Comment by robertying** [comment]
Wired support added.
Helper dcf5c9421be625b0b46832963983da9bb94cfaaa
Auto-login cf3cf7e72eae75deebb5c34107f7dd1ab9fcd490

**Comment by robertying** [comment]
Final release a02b5cfc7f97737bbe0eeeaec98755b5edf2e97e
[Release 1.4.0](https://github.com/robertying/dotNetCampus/releases/v1.4.0)
