### ISSUE TITLE
简化HttpClient的调用

### ISSUE THREAD

**Issue by Berrysoft** [robertying/dotNetCampus#4]
参见Microsoft对`HttpClient`的[解释](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.http.httpclient?view=netstandard-2.0)。

>HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly. 

代码中每次登录注销都要`new`一个，太浪费。

可以参考我的[ClassLibrary](https://github.com/Berrysoft/ClassLibrary)中的[Berrysoft.Tsinghua.Net](https://github.com/Berrysoft/ClassLibrary/tree/master/src/Berrysoft.Tsinghua.Net)的做法。

**Comment by Berrysoft** [comment]
@robertying

**Comment by robertying** [comment]
Closed by af20bf549f2ec1e16be51ffbec8d894a02027215
